### ISSUE TITLE
[BUG] Template Name as Variable

### ISSUE THREAD

**Issue by shunnmugam** [markmead/alpinejs-component#10]
How to keep template name as variable

`<template x-for="c in components">
      <x-component-wrapper
        x-component
        x-template="c.name"
        x-data="{ item: c }"></x-component-wrapper>
    </template>`

**Comment by markmead** [comment]
Oh, I'm not even sure that's possible but it's `template` not `x-template`. Hopefully that works 🤞

**Comment by markmead** [comment]
I've done some testing and it doesn't work as when you pass in `:template` it will read the value as `component.template`, or whatever variable you have passed in. However, I _think_ I have it working but not when passing a URL.

As this is the first time it's been asked about I believe just supporting `template` as an ID will be OK for now. What do you think?
