### ISSUE TITLE
Support recursive components

### ISSUE THREAD

**Issue by richcorbs** [markmead/alpinejs-component#12]
Nice work on this and thanks for it!

I'm trying to create a nested tree in my UI with parents, children, and grandchildren, etc. I can't get this to work for that use case. Something like this:

```
 <template id="node-component">
  <div>
    <h1 x-text="node.title"></h1>
    <template x-for="child in node.children">
      <x-component-wrapper
        x-component
        template="node-component"
        x-data="{ node: child }"
      ></x-component-wrapper>
    </template>
  </div>
</template>
```
In my case the parent's h1 renders but nothing else.

**Comment by markmead** [comment]
What is this for? It feels like you want a simple package to be a page renderer or something! 😅

**Comment by richcorbs** [comment]
Not sure what you mean "render the page" but for sure I want to render the
"tree" I'm creating.

**Comment by markmead** [comment]
Ah! I understand. I'd try the `url` approach in that case.

**Comment by richcorbs** [comment]
Does the plug-in cache the response? I wouldn't want to add an http request
per node in the tree.

**Comment by markmead** [comment]
Nope. Like I said it's a simple package. There might be others out there that do what you're after.

**Comment by markmead** [comment]
Yeah it works fine with `url`. 

Your choice on what to do but if you want it to work with `template` then it will need a PR.

**Comment by richcorbs-ncino** [comment]
Interesting. The code for template and url look very similar. Maybe I'm not using it right?

Would you mind pasting in the HTML (for the page and for the template) that you're using where you have recursion working with the url approach?

Just curious, does the same template used with the url approach work with recursion for the template approach?

**Comment by markmead** [comment]
Yeah, it's the same template but `url` works and `template` doesn't. I'm unsure why that would be as like you say, the code is very similar. I tried adding a modifier to allow for saving the `url` response to local storage but that was hitting the same issues `template` was.

**Comment by richcorbs-ncino** [comment]
The only difference I see between the template and the url is that the template waits for Alpine to initialize before firing:

```
        document.addEventListener('alpine:initialized', () => {
          Alpine.initTree(shadow)
        })
```

 Maybe it works the first time through because Alpine has not yet initialized, the event listener gets added, Alpine initializes and emits the event, and then initTree gets called. On subsequent times through the event listener never fires because Alpine has already initialized and doesn't emit the "alpine:initialized" event again. I don't yet see how to do it but what if there was logic like this for the template option:

```
     if (!Alpine.initialized) {
        document.addEventListener('alpine:initialized', () => {
          Alpine.initTree(shadow)
        })
    } else {
      Alpine.initTree(shadow)
    }
```

**Comment by markmead** [comment]
Good shout! I didn't think of that but turned out it didn't work, caused a "Uncaught" loop and froze Chrome! 😅

Found a solution while battling that, give it a try and let me know if it works! #13

**Comment by richcorbs** [comment]
Awesome!

I'm willing to try it out but not sure how. I think I need to somehow take
some (most?) of the code from index.js and add it to my project somewhere
locally.

Rich

**Comment by richcorbs** [comment]
Or can I link directly to the dist/component file?

**Comment by richcorbs** [comment]
To get this to work locally I did the following but that might just be a
result of adding it manually:

      if (!window.customElements.get('x-component-wrapper')) {
        customElements.define('x-component-wrapper', ComponentWrapper)
        Alpine.directive('component', () => new ComponentWrapper())
      }

The recursion worked great but the CSS wasn't applied to my html. The
classes were there but didn't get applied somehow.

**Comment by markmead** [comment]
Are you including the CSS within the `<template>`?

Did a check, it still works. You need to include CSS in the `<template>` as it uses the [shadow DOM](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM).

**Comment by richcorbs** [comment]
I included a "class" attribute with classes in the HTML but no style tags
in the template. It looks like the css classes aren't being applied because
the elements are shadow dom elements and the css classes (tailwind) aren't
targeted at the shadow dom.

It's not exactly the same as what the directive does but I also tried this
pattern and I'm super happy with how simple it is and how it turned out:

<template x-for="node in rootNodes" :key="node.id">
   <div x-html="renderComponent('node-component')"></div>
</template>

<script>
      .....
      renderComponent (templateId) {
        return document.getElementById(templateId).cloneNode(true).innerHTML
      }
</script

<template id="node-component">
  <div class="pl-4">
    <h3 x-text="node.title" class="py-2 px-4 text-sm hover:bg-gray-100
cursor-pointer"></h3>
    <template x-for="node in childrenNodes[node.id]" :key="node.id">
      <div x-html="renderComponent('node-component')"></div>
    </template>
  </div>
</template>

**Comment by markmead** [comment]
That's interesting... Does it maintain Alpine JS reactivity?

**Comment by richcorbs** [comment]
Yes! Reactivity is preserved! And CSS classes work too!

I think as long as the variables used within the component exist within the
scope where the component is being used everything works. In my case "node"
is available within the recursive x-for scope (not the parent x-for scope)
and "childrenNodes" is available from the root scope.

Originally I used x-for="child in childrenNodes" in the recursive
component. This caused an infinite loop because "node" (used within the
component) was available from the parent x-for. When I used x-for="node in
childrenNodes" in the recursive component it started working.

It seems clunky for a random, single-use "component" like a Vue component
with an x-for wrapper.

<template "x-for="node in [differentNode]"">
  <div x-html="renderComponent('my-component')"></div>
</template>

Or maybe x-component could work like this pseudo code:

<div x-component="my-component" x-data="{ data1: 'data' }"></div>

// plugin code
  this.attribute['x-component'].value // or however you get that value
  var el = document.getElementById("my-component")
  this.attribute('x-html', el.cloneNode(true).innerHTML)
// end plugin code

I'm going to play with that idea later today.

**Comment by richcorbs** [comment]
This worked:

        <template x-for="node in rootNodes" :key="node.id">
          <div x-component="node-component" x-data="{ node }"></div>
        </template>

<template id="node-component">
  <div class="pl-4">
    <h3 x-text="node.title" class="py-2 px-4 text-sm hover:bg-gray-100
cursor-pointer"></h3>
    <template x-for="node in childrenNodes[node.id]" :key="node.id">
      <div x-component="node-component" x-data="{ node }"></div>
    </template>
  </div>
</template>

<script>
        Alpine.directive('component', (el, { expression }, { evaluate }) =>
{
            var template =
document.getElementById(expression).cloneNode(true).innerHTML
            el.innerHTML = template
        })
</script>

I'm still exploring how to get data into this without having to use an
x-for.

**Comment by richcorbs** [comment]
This works too. It's simple and still gives me the ability to reuse a
"component" with all the capabilities of Alpine.

<template x-for="node in nodes" :key="node.id">
  <div x-html="renderComponent('node-component')"></div>
</template>

<template x-if="nodes[0]">
  <div x-html="renderComponent('node-component')" x-data="{ node:
rootNodes[0] }"></div>
</template>

<template id="node-component">
  <div class="pl-4" @click.stop="alert(node)">
    <h3 x-text="node.title" class="py-2 px-4 text-sm hover:bg-gray-100
cursor-pointer"></h3>
    <template x-for="node in childrenNodes[node.id]" :key="node.id">
      <div x-html="renderComponent('node-component')"></div>
    </template>
  </div>
</template>

**Comment by J3ronimo** [comment]
Hey. I saw you used `cloneNode` in your `renderComponent`. Wouldn't it suffice to just return the innerHTML of the template, without cloning it first? Also, the `template` has an `id` which the clone will also copy, which should lead to duplicate IDs in the DOM.

Anyway, great stuff! Especially with tailwind and the tons of css classes it adds to your html, having a component that you can place instances of into your page, without duplicating the base code, is absolutely brilliant. The final bit is that these components can instantiate other components, too, maybe even recursively, as this could completely eliminate the need for any server side rendering and templating. 😳
