### ISSUE TITLE
Is the `x-component-wrapper` necessary?

### ISSUE THREAD

**Issue by kevinruscoe** [markmead/alpinejs-component#15]
This plugin works great for me, but the need for both x-component-wrapper and x-component hurts my eyes.

Is there a reason why we can't bind custom fields on divs or sections? 

https://stackoverflow.com/a/67276585 works in a similar fashion. But uses the querySelector to bind the HTMLElement element. I'm thinking could we not uses a similar approach to late-bind the HTMLElement on found tags? That way we could just do <x-my-component x-component> and it'll bind HTMLElement to the x-my-component?

Thoughts?

**Comment by markmead** [comment]
Thanks for sharing @kevinruscoe but I'm not that interested in that approach, I like the clarity that `x-component-wrapper` gives. However, I'd be tempted to look into removing `x-component` and just have it init on `x-component-wrapper`. 

Maybe that's what you were suggesting, but the link took me to stuff like `x-dropdown`.

**Comment by kevinruscoe** [comment]
Removing the x-component directive and renaming x-componemt-wrapper to x-component would be a nice compromise.

**Comment by markmead** [comment]
Ha! It's an idea, not a compromise. I'll take a look.

**Comment by markmead** [comment]
Fancy giving this a spin? https://github.com/markmead/alpinejs-component/pull/16

**Comment by kevinruscoe** [comment]
^ That worked a treat, thanks @markmead
