### ISSUE TITLE
`x-component` directive conflicts with Laravel component directive

### ISSUE THREAD

**Issue by Cyrille37** [markmead/alpinejs-component#21]
Hello.

Thanks for this nice & useful package :-)

But the directive `x-component` conflicts with [Laravel Blade](https://laravel.com/docs/10.x/blade#rendering-components) :-(

Do you use it? Do you have any ideas on how to get round this problem?

Perhaps a configuration option to use in `window.customElements.get('x-component')` ?

Thanks & cheers

**Comment by markmead** [comment]
Hi @Cyrille37, thanks for highlighting this. Got a few questions: 

- Why are you using `x-component` when you have Blade components? 
- What does `x-component` solve that isn't possible with Blade?

**Comment by Cyrille37** [comment]
Thank you @markmead for your enlightening questions :-) U're right :100:

**Comment by Cyrille37** [comment]
Hello @markmead 
I come back on the subject ;-)

I would like to have both : Blade components and Alpine components.
- Blade are processed on the server side whereas Alpine are processed on client side.
- Some useful external packages are using Blade
- Some useful rendering could be on client side with Alpine
