### ISSUE TITLE
Failed to fetch external template URL

### ISSUE THREAD

**Issue by beliolfa** [markmead/alpinejs-component#22]
Hey, congrats for this plugin. It's just fantastic!

I am having some trouble trying to load an external HTML like this:

```
<x-component
        url="https://cdn.jsdelivr.net/npm/@invopop/alpine-kit@0.0.1/image-picker.html"
        x-data="{ url: 'https://placehold.co/40x40' }"
></x-component>
```
But I am getting an error `Uncaught (in promise) TypeError: Failed to fetch`

I am sure I am doing something wrong because the code below works:

```
fetch('https://cdn.jsdelivr.net/npm/@invopop/alpine-kit@0.0.1/image-picker.html')
          .then(response => response.text())
          .then(html => {
            console.log(html)
          })
          .catch(error => console.error('Error loading HTML:', error));
```

Thanks!

**Comment by markmead** [comment]
Not sure what to tell you, the example you gave works for me.

**Comment by beliolfa** [comment]
Hey, thanks for taking a look to it! Can you share with me what is your environment and your code and see what I am doing wrong? Thank you!

**Comment by markmead** [comment]
Just the example you gave and what's in the README.

**Comment by beliolfa** [comment]
Hello again, I understand that you closed this issue to keep the repo clean. As I mentioned above "I am sure I am doing something wrong" It would be great if you could help me with loading an external URL. Is this even supported? Documentation in the README only shows loading a local HTML file. I always get `failed to fetch` when trying to fetch a URL. It's probably my environment, server, cors, or whatever.

Thanks!

**Comment by markmead** [comment]
It was just an `index.html` file like this:

```html

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <script defer src="https://unpkg.com/alpinejs-component@latest/dist/component.min.js"></script>

    <script defer src="https://unpkg.com/alpinejs@3.x.x/dist/cdn.min.js"></script>
  </head>
  <body>
    <x-component
      url="https://cdn.jsdelivr.net/npm/@invopop/alpine-kit@0.0.1/image-picker.html"
      x-data="{ url: 'https://placehold.co/40x40' }"
    ></x-component>
  </body>
</html>
```
