### ISSUE TITLE
Templating and `x-component` fail to refresh on array manipulation

### ISSUE THREAD

**Issue by AurelienMarchand** [markmead/alpinejs-component#23]
taking the code given in the README and adding just one button that removes the first record in the array `people` and a button to dump the array to the console:

```
<div
  x-data="{
    people: [
      { name: 'John', age: '25', skills: ['JavaScript', 'CSS'] },
      { name: 'Jane', age: '30', skills: ['Laravel', 'MySQL', 'jQuery'] }
    ]
  }"
>
  <ul>
    <template x-for="person in people">
      <x-component template="person" x-data="{ item: person }"></x-component>
    </template>
  </ul>

  <!-- addition -->
  <p><button @click="people.splice(0,1)">Remove John</button></p>
  <p><button @click="console.dir(people)">Dump Array to Console</button></p>
  <!-- end of addition -->
</div>

<template id="person">
  <li>
    <h2 x-text="item.name"></h2>

    <p x-text="item.age"></p>

    <ul>
      <template x-for="skill in item.skills">
        <li x-text="skill"></li>
      </template>
    </ul>
  </li>
</template>
```

If you click the Remove button, the array is indeed dropping John and keeping Jane (verify by clicking the 2nd button), but the presentation keep John and removes Jane.

**Comment by markmead** [comment]
Been trying to fix this for the better part of an hour now, no luck and I'm out of ideas. I'll mark it as `help wanted`.

**Comment by AurelienMarchand** [comment]
my intuition is that the shadow root elements need to be first fully removed and then recreated

**Comment by markmead** [comment]
I was thinking something similar but couldn't get anything working. Any ideas?

**Comment by AurelienMarchand** [comment]
I am testing on my end a few approaches:
1. refreshing the shadow-root using shadowRoot.innerHTML = shadowRoot.innerHTML
2. maybe using the Morph alpineJS extension
3. investigating is Alpine.initTree is to blame or whether there is a way to call Alpine.destroyTree

**Comment by AurelienMarchand** [comment]
I found a workaround:

```
<div
  x-data="{
    people: [
      { name: 'John', age: '25', skills: ['JavaScript', 'CSS'] },
      { name: 'Jane', age: '30', skills: ['Laravel', 'MySQL', 'jQuery'] }
    ]
  }"
>
 <x-component template="person" x-data="{ persons: people }"></x-component>

  <!-- addition -->
  <p><button @click="people.splice(0,1)">Remove John</button></p>
  <p><button @click="console.dir(people)">Dump Array to Console</button></p>
  <!-- end of addition -->
</div>

<template id="person">
  <ul>
    <template x-for="item in persons">
  <li>
    <h2 x-text="item.name"></h2>

    <p x-text="item.age"></p>

    <ul>
      <template x-for="skill in item.skills">
        <li x-text="skill"></li>
      </template>
    </ul>
  </li>
    </template>
  </ul>
</template>
```

**Comment by markmead** [comment]
Hm, it seems like a solid approach which doesn't require a large amount of setup. How do you feel about it?

I'm quite surprised this issue hasn't come up before so maybe people are already doing this 🤔

**Comment by AurelienMarchand** [comment]
> How do you feel about it?

I feel it should be documented! I've lost a number of hours trying to address it so maybe add a simple sentence like: don't use x-component within a looping template, rather put the loop within the x-component template if possible

Other than that it worked great. One caveat: My code was trying to point to an item in the loop using the global address and index as such:

```
    <template x-for="(item,idx) in persons">
  <li>
    <h2 x-text=" 'Record #' + (1+idx) ':' + people[idx].name"></h2>
```
But that caused errors when removing records. I had to use `item.name` to stop the errors

**Comment by markmead** [comment]
You should be using `item.name` in that case. Why would you want to point to a variable outside the `x-for` loop?

**Comment by AurelienMarchand** [comment]
I was using `id` and `label` in the templating HTML and to avoid `id` collision, I used the `idx` as part of the identifier. As I was already using idx, I thought I could do it in the `x-model` attribute too.

For the record, I am using the approach I describe in the workaround above, everything is working well now. I am just detailing the trek it took to get there

Once the documentation is updated, I feel you could flag this issue as closed

**Comment by markmead** [comment]
I think we've been overthinking this! Give this a try:

```html
<div
  x-data="{
    people: [
      { id:'123', name: 'John', age: '25', skills: ['JavaScript', 'CSS'] },
      { id: '1234', name: 'Jane', age: '30', skills: ['Laravel', 'MySQL', 'jQuery'] }
    ]
  }"
>
  <button @click="people.splice(0, 1)">Delete</button>

  <ul>
    <template x-for="person in people" :key="person.id">
      <x-component template="person" x-data="{ item: person }"></x-component>
    </template>
  </ul>
</div>

<template id="person">
  <li>
    <h2 x-text="item.name"></h2>

    <p x-text="item.age"></p>

    <ul>
      <template x-for="skill in item.skills">
        <li x-text="skill"></li>
      </template>
    </ul>
  </li>
</template>
```

I was trying it with `(person, index) :key="index"` and it didn't like that, but specifying a unique key in `x-data` seems to be working for me. Let me know if it is OK for you.

**Comment by AurelienMarchand** [comment]
I can see why! I used to do this originally:

```
 <template x-for="(person, idx) in people" :key=idx">
      <x-component template="person" x-data="{ item: person, index:idx }"></x-component>
    </template>
```

So it makes sense the loop fails when the idx is no more because of array manipulation. I like your solution. That seals the issue for me.

**Comment by markmead** [comment]
Mmhm, it makes perfect sense now! Sorry I didn't clock onto that earlier, thanks for helping with this issue! 🙌
