### ISSUE TITLE
How to style with Tailwind CSS

### ISSUE THREAD

**Issue by go4cas** [markmead/alpinejs-component#24]
Hi @markmead, nice library! Makes Alpine components nice and simple!

I had a look at the docs on styling, but I am struggling to style the components with a utility lib like Tailwind.ccs, or UnoCSS (in my case). Any idea how I could apply styles from the utility lib in my components?

**Comment by markmead** [comment]
Example here - https://github.com/markmead/alpinejs-component/pull/25

**Comment by AurelienMarchand** [comment]
thanks to the example you provided, I reverted my hardcoding of the stylesheet into the component.min.js

**Comment by go4cas** [comment]
Thanks for the example, @markmead! Is similar achievable without package managers, and using the CDN?

**Comment by markmead** [comment]
> Thanks for the example, @markmead! Is similar achievable without package managers, and using the CDN?

~Not really without loading the CDN version into the components. If you're OK with that then it should be A-OK.~

Ignore that, it's a `<script>` tag. Erm, I don't think so then.

**Comment by hoangcp8700** [comment]
I just use cdn to build includes html, css and integrate AlpineJS CDN, so how to fix it with CDN?
