### ISSUE TITLE
Override the `x-component` directive

### ISSUE THREAD

**Issue by Cyrille37** [markmead/alpinejs-component#27]
Hello

Because our toolchain depends on more and more packages it could be nice to permits the overriding of the custom element name `x-component`. An example need is quoted in #21 ;-)

I found this change do the job:

```javascript
 ...
  let tagName = Alpine.store('alpinejs-component.tagName');
  if( ! tagName )
    tagName = 'y-component';
  if (window.customElements.get(tagName)) {
    return
  }

  customElements.define(tagName, ComponentWrapper)
 ...
```

then before loading the plugin we can set another tag name like "z-component" with

```javascript
Alpine.store('alpinejs-component.tagName', 'z-component');
Alpine.plugin(component)
```

I can purpose a PR if you agree with this proposal ;-)

Thanks & cheers

**Comment by Cyrille37** [comment]
Perhaps this proposition is not compatible with CDN use, but I did not find another way :-(

**Comment by Cyrille37** [comment]
I'm asking [here](https://github.com/alpinejs/alpine/discussions/4176) what's the right way to pass settings to a plugin.

**Comment by markmead** [comment]
Hello @Cyrille37, thanks for taking the time to write this up.

I'm not a fan of the approach shown, relying on the store is not something I have interest in. I like how the project is built. In a way it's independent, it just uses Alpine JS to make using the underlying JavaScript easier.

If you can find a way that allows users to pass in an override within `Alpine.plugin(component)`, then I'd be interested. As it stands, your best bet is to clone the project, modify it and then upload it to NPM. Ideally, making note of the existing, original package.

**Comment by markmead** [comment]
You could use the `@component` directive as an alternative.

**Comment by markmead** [comment]
Wanna give this #28 a spin? @Cyrille37

**Comment by Cyrille37** [comment]
Yes, that's it :-)

**Comment by Cyrille37** [comment]
> You could use the @component directive as an alternative.

Unfortunately Laravel Blade has appropriated the symbol `@` :(
```
 <div x-data @component template="person" x-data="{ item: person }"></y-component>
```
Throw a `ErrorException: Undefined property: Illuminate\View\Factory::$startComponent`

I really think a custom component name is mandatory to be compatible with different frameworks. The PR #28 will do the job, and I'll be able to use a namespaced name like "<alpinejs:component />" ;-)

Thanks for code & discussion <3

**Comment by Cyrille37** [comment]
> The PR #28 will do the job, and I'll be able to use a namespaced name like "<alpinejs:component /

Sadly, namespaced name is not compatible as said in [documentation](https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/define#valid_custom_element_names) and [specification](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name):
```
Uncaught DOMException: CustomElementRegistry.define: 'alpine:component'
is not a valid custom element name
```

So I'll use `alpine-component` :-)

**Comment by markmead** [comment]
No no, you can render components in Blade with `@component`. It was removed from the documentation a few years back but it should still be supported.
