### ISSUE TITLE
Unable to use `styles="global"` with Tailwind CSS

### ISSUE THREAD

**Issue by dowhileweb** [markmead/alpinejs-component#29]
Hello, 
Im trying to use styles="global" with tailwindcss cdn:

`<link href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css" rel="stylesheet">`

But the component can't see tailwind's classes.
Is there a way to use tailwind's classes inside component code?

**Comment by mdn522** [comment]
Hey, did you find any solution?

Thank you
