### ISSUE TITLE
Reactivity for x-model?

### ISSUE THREAD

**Issue by Hrishikesh-K** [markmead/alpinejs-component#4]
Hi!

Thanks for this plugin, this gets me so-close to client-side templating without any frameworks or libraries like Vue or React.

However, this might have to do with my setup, but it appears that this won't work fine with `x-model` directive. Here's what I'm trying:

My HTML file includes:

```html
<html
  x-data = "alpine">
  <body>
    <x-component-wrapper
      x-component
      url = "/components/input/">
    </x-component-wrapper>
  </body>
</html>
```

My template file has the following:

```html
<div>
  <link
    href = "/css/bundle.css"
    rel = "stylesheet"/>
  <input
    x-model = "input"/>
</div>
```

I've my Alpine data model in my JavaScript bundle:

```js
import Alpine from 'alpinejs'
import Component from 'alpinejs-component'
Alpine.data('alpine', () => ({
  input: null
}))
Alpine.plugin(Component)
Alpine.start()
```

Now, I'm not sure how to bind the `x-model` to the `<input>`. Directly using `x-model = "input"` in my component works, however I need to be able to change the `x-model = "<value>"` for each of my `<input>` element. Any guidance would be super helpful! Also, I hope this is possible with the plugin because this would make developer experience so much better for my website made with Hugo. Currently, I've to copy-paste my input element several times and it's getting difficult to manage as I need to update all of those for a single change.

But if it's not possible, I totally understand. The plugin seems to be great at what it's doing and I appreciate the work that's put into this.

**Comment by markmead** [comment]
Hey @Hrishikesh-K 

Something like this would work:

```html
<div x-data="{ name: 'Mark' }">
  <x-component-wrapper x-component url="name.html"></x-component-wrapper>
  <x-component-wrapper x-component url="name.html"></x-component-wrapper>
  <x-component-wrapper x-component url="name.html"></x-component-wrapper>
</div>
```

Then in the component:

```html
<input type="text" x-model="name" />
```

**Comment by Hrishikesh-K** [comment]
Hey @markmead,

Thank you for taking time to respond. However, that was not what I was referring to. I've tried to put together an example here: https://github.com/Hrishikesh-K/components

Note that, it uses Hugo as the tool to build the site, so you might need that installed if you wish to try it. You can simply clone the repo, and run `npm i && npm run dev`. If it fails in the first time complaining about `styles.css`, you can simply run `npm dev` again.

So let me explain what I've done in there.

If you check: https://github.com/Hrishikesh-K/components/blob/main/assets/js/bundle.js, you will see that I've defined an `Alpine.data()` for my site. In that, I've got `input1` as one of the `x-models` that I need to use.

In this file: https://github.com/Hrishikesh-K/components/blob/main/layouts/index.html#L35-L38, I'm referencing my component and passing the data from my global Alpine instance as a local `x-data` to this component.

Finally, if you check: https://github.com/Hrishikesh-K/components/blob/main/layouts/components/input.html, you'd see that I'm using the `x-model` passed along with `x-data` in my component wrapper, and while that might be working as intended, my original, global-scoped `input1` remains `null`. You can try that by selecting the `html` element in the element inspector and run `$0._x_dataStack[0].input1` in the browser's console.

This might have to do with how Alpine works and little to do with how your plugin works, but I'm not skilled enough to decide that. 😉

**Comment by markmead** [comment]
OK, I _think_ we may be onto something... https://github.com/markmead/alpinejs-component-global-data

Should be able to pull this down and run `serve`, you might need to install it via `npm i -g serve`.

**Comment by Hrishikesh-K** [comment]
Sorry for the delay. That's an interesting approach and it works perfectly! Thanks you so much!
