### ISSUE TITLE
[BUG] Issue Building with Vite

### ISSUE THREAD

**Issue by TheBigRoomXXL** [markmead/alpinejs-component#6]
I have installed the plugin with a package manager and created a basic component : 
```html
<div x-data="tabs">
  <link rel="stylesheet" href="/assets/classless.css">
  <nav>
    <ul>
      <img alt="app_logo"
       src="../assets/logo.svg" />
      <span style="font-size: 1.5em ">rlog</span>
      <template x-for="tab in tabs">
        <li x-text="tab"></li>
      </template>
      <img class="float-right" alt="RFC logo" src="../assets/Logo_RFC_Couleur_Blanc.png"  />
    </ul>
  </nav>
</div>
```

I use it inside my index.html
```html
<x-component-wrapper 
      x-component
      url="../components/Navbar.html"
></x-component-wrapper>
```

When I use `npm run dev` (vite --host 0.0.0.0 --port 3000) it work fine but when I use `npm run build` (vite build) it break because the url  "../components/Navbar.html" doesn't exist anymore. 

I try fixing that by adding the component to the static assets with `assetsInclude: ['/components/*.html']` in vite.config.js but it didn't work for several reasons : 
- A hash is added to the file name
- The file is then stored in the assets folder, not 'components/'
- The links inside are not process so there are broken

Is there a way to fix that so I can steel use Vite to build? 

My vite.config.js
```javascript
import { resolve } from 'path'
import { defineConfig } from 'vite'

export default defineConfig({ 
  root : resolve(__dirname, 'app/'),
  build: {
    outDir : resolve(__dirname, 'dist/'),
    emptyOutDir: true,
  }
})
```

Thank you!

**Comment by markmead** [comment]
Hey @TheBigRoomXXL 👋 

Sorry I missed this. Just for future reference, make sure you assign an issue/PR to get attention.

I've not used Vite like this, do you have an example repo?
