### ISSUE TITLE
[Not an issue] Shadow DOM

### ISSUE THREAD

**Issue by jikkujose** [markmead/alpinejs-component#8]
Everything was great till I read this technique will not support global CSS. Its such a shame! I was hoping every issue was getting solved right here! Its a pain to see how Global CSS is not supported by Shadow DOM! I wish there was some workaround.

One question: If I have linked a CSS file in main page, and component also links to the same file will it get redownloaded by the browser or will it be taken from the cache?

**Comment by markmead** [comment]
Hi @jikkujose yeah it's very frustrating. 

As for your question, I have no idea. I've not looked into the shadow DOM too much, but there is some interesting information here about the topic - https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM#internal_versus_external_styles

**Comment by biowaffeln** [comment]
Hey Mark! Thanks for this cool library, I'm currently working on a project that uses Tailwind and I've hit the same road block with global CSS. However, I've seen this cool technique by @natemoo-re for passing in global CSS into the shadow DOM root, you can check it out here: https://github.com/natemoo-re/magic-element/blob/3cc6d2773fbbf90f680c8ec0855b4c2e9f1149ce/packages/magic-element/src/index.ts#L115C1-L115C1

It basically captures the global style sheets and applies them to the shadow root, which solves this problem! You should consider adding this to your project as well.
